### ISSUE TITLE
开机报错

### ISSUE THREAD

**Issue by MXJNZ6** [sirpdboy/netspeedtest#1]
n1编译了之后开机报错
/usr/lib/lua/luci/dispatcher.lua:527: Invalid controller file found
The file '/usr/lib/lua/luci/controller/NetSpeedTest.lua' contains an invalid module line.
Please verify whether the module name is set to 'luci.controller.NetSpeedTest' - It must correspond to the file path!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:527: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:553: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:238: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by sirpdboy** [comment]
重新下载 编译即可，原来的大小写的问题已经 解决。
