### ISSUE TITLE
readme中安装 luci-app-NetSpeedTest 貌似应为 luci-app-netspeedtest

### ISSUE THREAD

**Issue by mysteryman2045** [sirpdboy/netspeedtest#10]
# 更新feeds，并安装主题：
  scripts/feeds update NetSpeedTest
  scripts/feeds install luci-app-NetSpeedTest

执行  scripts/feeds install luci-app-NetSpeedTest 会提示
WARNING: No feed for package 'luci-app-NetSpeedTest' found

但是 改成全小写  scripts/feeds install luci-app-netspeedtest 就OK了 😂

**Comment by sirpdboy** [comment]
好的。感谢 提醒，已经修改好。
