### ISSUE TITLE
新版编译不成功了

### ISSUE THREAD

**Issue by mmeiwenlong** [sirpdboy/netspeedtest#12]
前阵子还可以。自这两天更新后就不
![QQ截图20211002111245](https://user-images.githubusercontent.com/44661424/135701916-ff87a0a2-fb8c-4e3b-bb8e-063cfc4413af.png)
行了

**Comment by mmeiwenlong** [comment]
求帮助

**Comment by mmeiwenlong** [comment]
![QQ截图20211005102503](https://user-images.githubusercontent.com/44661424/135954165-4ca5ccbf-e592-4636-9221-bcf538312161.png)

**Comment by sirpdboy** [comment]
问题已经解决，重新下载编译即可。

**Comment by mmeiwenlong** [comment]
谢谢，可以了
