### ISSUE TITLE
bypass选择了Gfw模式，外网测速走了代理

### ISSUE THREAD

**Issue by gzxiexl** [sirpdboy/netspeedtest#14]
可否告知一下外网测速的域名，添加到直连列表去，我已经把Speedtest.net加入直连貌似您用的不是

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by sirpdboy** [comment]
这个自动选择服务器的哦。

**Comment by sirpdboy** [comment]
这是自动获取的列表。。
