### ISSUE TITLE
测试速度似乎不太准

### ISSUE THREAD

**Issue by EricNg8801** [sirpdboy/netspeedtest#17]
R4s， 也是大佬您的固件（220301），有运行Openclash（Tun+啥混合忘了）
测试只有个位数的速度，我的线路是电信千兆，自行登录speedtest.net测有700左右
![image](https://user-images.githubusercontent.com/90168131/163557083-4a232e0a-0cde-4f17-a8eb-425812e7b26a.png)

**Comment by naoki66** [comment]
因为你用的机场。这个结论是你机场的速度。
不知道什么时候可以开放自定义server ID 进行测速。

**Comment by EricNg8801** [comment]
> 因为你用的机场。这个结论是你机场的速度。 不知道什么时候可以开放自定义server ID 进行测速。

我关了小猫他还是走国外，人傻了

**Comment by sirpdboy** [comment]
这测试是自动判断，有时候可能判断错误 。。后期看需要和时间来，可以加参数等 。。

**Comment by rainchensh** [comment]
我的也是，电信500M的套餐，非常不准。下载速度有时还没上传速度快。上传速率正确
![image](https://user-images.githubusercontent.com/81663884/221079490-1f429784-694a-44bc-b0ef-cbd64f0ca2ba.png)
