### ISSUE TITLE
外网测速被代理

### ISSUE THREAD

**Issue by naoki66** [sirpdboy/netspeedtest#18]
默认情况下 。speedtest.net会被机场代理、
加入了规则。内网其他客户端都可以正常识别国内的server ID。
但是这个还是只有外网的，也就是指定不走代理无效。

**Comment by naoki66** [comment]
另外是否可以开放指定服务器ID呢？命令行是可以的。因为它本身的遥测问题经常会失效。

**Comment by sirpdboy** [comment]
要弄参数 也是可以，后期有时间 考虑升级。
