### ISSUE TITLE
lean源码编译后不能正常登陆

### ISSUE THREAD

**Issue by tianiue** [sirpdboy/netspeedtest#2]
![11](https://user-images.githubusercontent.com/61725402/113079148-17673c00-9207-11eb-9860-ae5b8f71065f.png)
请作者修复，谢谢

**Comment by bluestar800** [comment]
scp进入 /usr/lib/lua/luci/controller/
把NetSpeedTest.lua全部改成小写netspeedtest.lua，保存，刷新网页就可以了。

**Comment by sirpdboy** [comment]
删除重新上传了，大小写的问题已经修正。
