### ISSUE TITLE
2个疑问点

### ISSUE THREAD

**Issue by wangweitung** [sirpdboy/netspeedtest#20]
1、客户端软件，能否设置默认的服务端地址？避免每次都要手动输入。
2、测速包大小是10M，能否手动设定？

**Comment by sirpdboy** [comment]
客户端这个是一个批处理脚本。每个人的环境不一样，不能指定IP。
测速包的大小等在客户端批处理脚本 ，自己修改就可以了。
目前升级了 新版本。你可以再试试。
