### ISSUE TITLE
尚无任何配置

### ISSUE THREAD

**Issue by Link-HXX** [sirpdboy/netspeedtest#24]
如图，内网测速网页版和内网iperf3吞吐测速下面均只显示，尚无任何配置，并没有其他图文了。

<img width="1716" alt="i1" src="https://user-images.githubusercontent.com/47153280/199760612-4bfc5ae4-a1a7-4a1f-b143-d5baac57f1f8.png">
<img width="1719" alt="i2" src="https://user-images.githubusercontent.com/47153280/199760745-68535049-0219-4013-b55b-fc3bf6d7b265.png">

请问这个怎么办？

**Comment by sirpdboy** [comment]
少了配置文件。

**Comment by Link-HXX** [comment]
那该怎么办呢？

**Comment by sirpdboy** [comment]
是安装的话， 要在/ETC/CONFIG/中手动上传 配置文件，下个版本可以考虑判断配置文件问题自己生成 。
