### ISSUE TITLE
云编译报错

### ISSUE THREAD

**Issue by naoki66** [sirpdboy/netspeedtest#29]
Finding targets

Building targets

/workdir/openwrt/staging_dir/host/bin/upx --lzma --best /workdir/openwrt/build_dir/target-x86_64_musl/speedtest-web-1.1.5/.go_work/build/bin/speedtest
bash: line 1: /workdir/openwrt/staging_dir/host/bin/upx: No such file or directory
make[3]: *** [Makefile:79: /workdir/openwrt/build_dir/target-x86_64_musl/speedtest-web-1.1.5/.built] Error 127
make[3]: Leaving directory '/workdir/openwrt/feeds/netspeedtest/speedtest-web'
time: package/feeds/netspeedtest/speedtest-web/compile#1.07#0.42#1.20
    ERROR: package/feeds/netspeedtest/speedtest-web failed to build.
make[2]: Leaving directory '/workdir/openwrt'
make[2]: *** [package/Makefile:116: package/feeds/netspeedtest/speedtest-web/compile] Error 1
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by firkerword** [comment]
+1

**Comment by hououinkami** [comment]
+1

**Comment by hwliu11** [comment]
把speedtest-web下Makefile中PKG_BUILD_DEPENDS:=golang/host这一句加上 upx/host
lean那边代码把重复的upx包删除了，加上upx/host编译本机upx
