### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by fuwa2019** [sirpdboy/netspeedtest#33]
![image](https://user-images.githubusercontent.com/56064365/213353882-0e512d2e-321d-492d-8f04-ccd7c1599ad8.png)

**Comment by fuwa2019** [comment]
[log.txt](https://github.com/sirpdboy/netspeedtest/files/10453518/log.txt)
这是单独编译的完整log

**Comment by KevinMX** [comment]
`sudo apt -y install npm`

**Comment by lqzhj** [comment]
try：

sudo apt -y install npm

export GO111MODULE=on
export GOPROXY=https://goproxy.cn
 
ref：  https://github.com/goproxy/goproxy.cn/blob/master/README.zh-CN.md

**Comment by fuwa2019** [comment]
> try：
> 
> sudo apt -y install npm
> 
> export GO111MODULE=on export GOPROXY=https://goproxy.cn
> 
> ref： https://github.com/goproxy/goproxy.cn/blob/master/README.zh-CN.md

thanks
