### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Canary233** [sirpdboy/netspeedtest#34]
make[3]: Entering directory '/home/lu/data/source/lede_new/feeds/netspeedtest/homebox'
mkdir -p /home/lu/data/source/lede_new/dl
SHELL= flock /home/lu/data/source/lede_new/tmp/.homebox-0.0.0-dev.2020062901.tar.gz.flock -c '          /home/lu/data/source/lede_new/scripts/download.pl "/home/lu/data/source/lede_new/dl" "homebox-0.0.0-dev.2020062901.tar.gz" "skip" "v0.0.0-dev.2020062901.tar.gz" "https://github.com/XGHeaven/homebox/archive/refs/tags/"    '
rm -f /home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901/.built
touch /home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901/.built_check
rm -rf /home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901/build/static
mkdir -p /home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901/build
cp -fpR /home/lu/data/source/lede_new/build_dir/hostpkg/homebox/build/static /home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901/build/
( cd /home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901; GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901=homebox-0.0.0-dev.2020062901 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/lu/data/source/lede_new/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/lu/data/source/lede_new/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/lu/data/source/lede_new/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901=homebox-0.0.0-dev.2020062901 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/lu/data/source/lede_new/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/lu/data/source/lede_new/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro" GOPATH="/home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901/.go_work/build" GOCACHE="/home/lu/data/source/lede_new/tmp/go-build" GOMODCACHE="/home/lu/data/source/lede_new/dl/go-mod-cache" GOENV=off GO111MODULE=auto PATH=/home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901/.go_work/build/bin:$PATH make build-server; )
make[4]: Entering directory '/home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901'
go-bindata -fs -o server/assets.go -prefix build/static build/static
flag provided but not defined: -fs
  -debug
        Do not embed the assets, but provide the embedding API. Contents will still be loaded from disk.
  -dev
        Similar to debug, but does not emit absolute paths. Expects a rootDir variable to already exist in the generated code's package.
Usage: go-bindata [options] <input directories>

  -ignore value
        Regex pattern to ignore
  -mode uint
        Optional file mode override for all files.
  -modtime int
        Optional modification unix timestamp override for all files.
  -nocompress
        Assets will *not* be GZIP compressed when this flag is specified.
  -nomemcopy
        Use a .rodata hack to get rid of unnecessary memcopies. Refer to the documentation to see what implications this carries.
  -nometadata
        Assets will not preserve size, mode, and modtime info.
  -o string
        Optional name of the output file to be generated. (default "./bindata.go")
  -pkg string
        Package name to use in the generated code. (default "main")
  -prefix string
        Optional path prefix to strip off asset names.
  -tags string
        Optional set of build tags to include.
  -version
        Displays version information.
make[4]: *** [Makefile:24: build-assets] Error 2
make[4]: Leaving directory '/home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901'
make[3]: *** [Makefile:91: /home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901/.built] Error 2
make[3]: Leaving directory '/home/lu/data/source/lede_new/feeds/netspeedtest/homebox'
time: package/feeds/netspeedtest/homebox/compile#0.17#0.06#0.21
    ERROR: package/feeds/netspeedtest/homebox failed to build.
make[2]: *** [package/Makefile:116: package/feeds/netspeedtest/homebox/compile] Error 1
make[2]: Leaving directory '/home/lu/data/source/lede_new'
make[1]: *** [package/Makefile:110: /home/lu/data/source/lede_new/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lu/data/source/lede_new'
make: *** [/home/lu/data/source/lede_new/include/toplevel.mk:231：world] 错误 2

**Comment by sirpdboy** [comment]
homebox 我这编译 没问题。。

**Comment by zhugunzi** [comment]
我复现了  Entering directory '/home/lu/data/source/lede_new/build_dir/target-x86_64_musl/homebox-0.0.0-dev.2020062901'
go-bindata -fs -o server/assets.go -prefix build/static build/static
flag provided but not defined: -fs
