### ISSUE TITLE
内网测速不能显示

### ISSUE THREAD

**Issue by ufk119** [sirpdboy/netspeedtest#35]
![image](https://user-images.githubusercontent.com/55911453/216328151-f666336e-08b7-42e6-9878-0f3f1747bf16.png)

内网测速无法打开，显示缺少配置。
之前不基于homebox的是ok的。
即使另外安装了homebox并启用，还是不能够显示。

**Comment by sirpdboy** [comment]
你这是没有配置文件 导致。。

**Comment by ufk119** [comment]
> 你这是没有配置文件 导致。。

确实，通过对比老版本，然后导入配置解决。不过问题还是因为当时这个版本缺失配置文件。感谢回复。

**Comment by BoBppy** [comment]
> > 你这是没有配置文件 导致。。
> 
> 确实，通过对比老版本，然后导入配置解决。不过问题还是因为当时这个版本缺失配置文件。感谢回复。

请问具体要怎么做
