### ISSUE TITLE
编译出错，望大佬指点。

### ISSUE THREAD

**Issue by cyzzc** [sirpdboy/netspeedtest#36]
Ubuntu 22.04，试了很多次都是这情况。
![image](https://user-images.githubusercontent.com/80954721/223738653-e11d09d0-8638-4df7-8153-39d58763cd23.png)

**Comment by bingbinghj** [comment]
![image](https://user-images.githubusercontent.com/77175750/223867380-0103e0e2-17c1-4958-aff3-189ec27e2230.png)
![image](https://user-images.githubusercontent.com/77175750/223868079-d2ca49c0-e4cc-4625-affa-e50da1acc008.png)
sudo apt install npm -y 安装npm看一下，我之前也是homebox出错，安装了npm就编译成功了。
