### ISSUE TITLE
Netperf宽带测速和Speedtest宽带测速问题

### ISSUE THREAD

**Issue by bauw2008** [sirpdboy/netspeedtest#38]
5.15.98版本 
PKG_VERSION:=2.1.3
PKG_RELEASE:=20230302
PKG_MAINTAINER:=<https://github.com/sirpdboy/netspeedtest>

speedtest测速
  测服信息:  延时：
  下行速率:  ----  上行速率:
  测试时间: 2023-03-17 20:00:42
  ————————————————————————————

  netperf测速
  测服信息:netperf.bufferbloat.net  协议:(ipv4)  线程:4 
  下行速率: Mbps  ----  上行速率: Mbps
  测试时间: 2023-03-17 20:00:48
  ————————————————————————————

测速无结果。

**Comment by AE86JAY** [comment]
5.4内核一样是无结果

**Comment by AE86JAY** [comment]
> 5.15.98版本 PKG_VERSION:=2.1.3 PKG_RELEASE:=20230302 PKG_MAINTAINER:=https://github.com/sirpdboy/netspeedtest
> 
> speedtest测速 测服信息: 延时： 下行速率: ---- 上行速率: 测试时间: 2023-03-17 20:00:42 ————————————————————————————
> 
> netperf测速 测服信息:netperf.bufferbloat.net 协议:(ipv4) 线程:4 下行速率: Mbps ---- 上行速率: Mbps 测试时间: 2023-03-17 20:00:48 ————————————————————————————
> 
> 测速无结果。

经测试必须要路由拨号才行，AP模式测速就会没结果。
