### ISSUE TITLE
R23.5.1 编译成功后，web里面看不到插件

### ISSUE THREAD

**Issue by xiaoqi2020** [sirpdboy/netspeedtest#39]
R23.5.1 编译成功后，web里面看不到插件
![image](https://github.com/sirpdboy/netspeedtest/assets/50669177/b91b923d-efb9-4c7f-a563-b6f65fbc75d4)
![image](https://github.com/sirpdboy/netspeedtest/assets/50669177/8a61c46b-d110-45c6-a609-d67a211ec4e9)

**Comment by OldCoding** [comment]
![image](https://github.com/sirpdboy/netspeedtest/assets/85047508/a05070ec-a4ea-4072-9c39-fe7032aa2c50)

**Comment by xiaoqi2020** [comment]
> ![image](https://user-images.githubusercontent.com/85047508/243160713-a05070ec-a4ea-4072-9c39-fe7032aa2c50.png)

![image](https://github.com/sirpdboy/netspeedtest/assets/50669177/7bbf4b82-a57b-464c-ba71-89d99db85cfc)
后面两个都不显示内容呢？

**Comment by OldCoding** [comment]
![image](https://github.com/sirpdboy/netspeedtest/assets/85047508/0845fa7e-a173-4a21-a992-8c461c50355d)
是这样的，只有个按钮，点了后就在后台自动测速，测完就显示出来

**Comment by xiaoqi2020** [comment]
> ![image](https://user-images.githubusercontent.com/85047508/244273889-0845fa7e-a173-4a21-a992-8c461c50355d.png) 是这样的，只有个按钮，点了后就在后台自动测速，测完就显示出来

我的就是测试完了也不显示
![image](https://github.com/sirpdboy/netspeedtest/assets/50669177/871ca695-0f16-475d-80a4-32a938694c24)

**Comment by OldCoding** [comment]
> > ![image](https://user-images.githubusercontent.com/85047508/244273889-0845fa7e-a173-4a21-a992-8c461c50355d.png) 是这样的，只有个按钮，点了后就在后台自动测速，测完就显示出来
> 
> 我的就是测试完了也不显示 ![image](https://user-images.githubusercontent.com/50669177/244274186-871ca695-0f16-475d-80a4-32a938694c24.png)

你看下能不能访问https://www.speedtest.net/

**Comment by xiaoqi2020** [comment]
> > > ![image](https://user-images.githubusercontent.com/85047508/244273889-0845fa7e-a173-4a21-a992-8c461c50355d.png) 是这样的，只有个按钮，点了后就在后台自动测速，测完就显示出来
> > 
> > 
> > 我的就是测试完了也不显示 ![image](https://user-images.githubusercontent.com/50669177/244274186-871ca695-0f16-475d-80a4-32a938694c24.png)
> 
> 你看下能不能访问https://www.speedtest.net/

可以访问的
![image](https://github.com/sirpdboy/netspeedtest/assets/50669177/11d743dd-a7b8-444f-bcab-6149a471ecf4)

**Comment by OldCoding** [comment]
> > > > ![image](https://user-images.githubusercontent.com/85047508/244273889-0845fa7e-a173-4a21-a992-8c461c50355d.png) 是这样的，只有个按钮，点了后就在后台自动测速，测完就显示出来
> > > 
> > > 
> > > 我的就是测试完了也不显示 ![image](https://user-images.githubusercontent.com/50669177/244274186-871ca695-0f16-475d-80a4-32a938694c24.png)
> > 
> > 
> > 你看下能不能访问https://www.speedtest.net/
> 
> 可以访问的 ![image](https://user-images.githubusercontent.com/50669177/244274643-11d743dd-a7b8-444f-bcab-6149a471ecf4.png)

你看下系统日志里面在测速的那个时间有没有什么报错信息

**Comment by xiaoqi2020** [comment]
> > ![image](https://user-images.githubusercontent.com/85047508/244273889-0845fa7e-a173-4a21-a992-8c461c50355d.png) 是这样的，只有个按钮，点了后就在后台自动测速，测完就显示出来
> 
> 我的就是测试完了也不显示 ![image](https://user-images.githubusercontent.com/50669177/244274186-871ca695-0f16-475d-80a4-32a938694c24.png)

Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]: Traceback (most recent call last):
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 2004, in <module>
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:     main()
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 1990, in main
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:     shell()
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 1876, in shell
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:     speedtest = Speedtest(
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 1095, in __init__
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:     self.get_config()
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 1125, in get_config
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:     uh, e = catch_request(request, opener=self._opener)
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 730, in catch_request
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:     uh = _open(request)
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/urllib/request.py", line 519, in open
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 537, in http_open
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:     return self.do_open(
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 1282, in request
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 975, in send
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 426, in connect
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:     self.sock = socket.create_connection(
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/socket.py", line 824, in create_connection
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
Thu Jun  8 13:44:38 2023 daemon.err uhttpd[2457]: LookupError: unknown encoding: idna
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]: Traceback (most recent call last):
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 2004, in <module>
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:     main()
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 1990, in main
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:     shell()
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 1876, in shell
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:     speedtest = Speedtest(
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 1095, in __init__
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:     self.get_config()
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 1125, in get_config
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:     uh, e = catch_request(request, opener=self._opener)
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 730, in catch_request
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:     uh = _open(request)
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/urllib/request.py", line 519, in open
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 537, in http_open
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:     return self.do_open(
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 1282, in request
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/http/client.py", line 975, in send
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/bin/speedtest", line 426, in connect
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:     self.sock = socket.create_connection(
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/socket.py", line 824, in create_connection
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]:   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
Thu Jun  8 13:44:39 2023 daemon.err uhttpd[2457]: LookupError: unknown encoding: idna

**Comment by xiaoqi2020** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/85047508/244273889-0845fa7e-a173-4a21-a992-8c461c50355d.png) 是这样的，只有个按钮，点了后就在后台自动测速，测完就显示出来
> > > > 
> > > > 
> > > > 我的就是测试完了也不显示 ![image](https://user-images.githubusercontent.com/50669177/244274186-871ca695-0f16-475d-80a4-32a938694c24.png)
> > > 
> > > 
> > > 你看下能不能访问https://www.speedtest.net/
> > 
> > 
> > 可以访问的 ![image](https://user-images.githubusercontent.com/50669177/244274643-11d743dd-a7b8-444f-bcab-6149a471ecf4.png)
> 
> 你看下系统日志里面在测速的那个时间有没有什么报错信息
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: Traceback (most recent call last):
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 2004, in
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: main()
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1990, in main
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: shell()
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1876, in shell
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: speedtest = Speedtest(
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1095, in init
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: self.get_config()
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1125, in get_config
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: uh, e = catch_request(request, opener=self._opener)
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 730, in catch_request
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: uh = _open(request)
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 519, in open
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 537, in http_open
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: return self.do_open(
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1282, in request
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 975, in send
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 426, in connect
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: self.sock = socket.create_connection(
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/socket.py", line 824, in create_connection
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: LookupError: unknown encoding: idna
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: Traceback (most recent call last):
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 2004, in
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: main()
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1990, in main
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: shell()
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1876, in shell
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: speedtest = Speedtest(
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1095, in init
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: self.get_config()
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1125, in get_config
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: uh, e = catch_request(request, opener=self._opener)
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 730, in catch_request
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: uh = _open(request)
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 519, in open
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 537, in http_open
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: return self.do_open(
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1282, in request
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 975, in send
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 426, in connect
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: self.sock = socket.create_connection(
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/socket.py", line 824, in create_connection
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: LookupError: unknown encoding: idna

**Comment by xiaoqi2020** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/85047508/244273889-0845fa7e-a173-4a21-a992-8c461c50355d.png) 是这样的，只有个按钮，点了后就在后台自动测速，测完就显示出来
> > > > 
> > > > 
> > > > 我的就是测试完了也不显示 ![image](https://user-images.githubusercontent.com/50669177/244274186-871ca695-0f16-475d-80a4-32a938694c24.png)
> > > 
> > > 
> > > 你看下能不能访问https://www.speedtest.net/
> > 
> > 
> > 可以访问的 ![image](https://user-images.githubusercontent.com/50669177/244274643-11d743dd-a7b8-444f-bcab-6149a471ecf4.png)
> 
> 你看下系统日志里面在测速的那个时间有没有什么报错信息

Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: Traceback (most recent call last):
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 2004, in
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: main()
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1990, in main
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: shell()
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1876, in shell
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: speedtest = Speedtest(
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1095, in init
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: self.get_config()
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1125, in get_config
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: uh, e = catch_request(request, opener=self._opener)
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 730, in catch_request
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: uh = _open(request)
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 519, in open
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 537, in http_open
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: return self.do_open(
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1282, in request
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 975, in send
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 426, in connect
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: self.sock = socket.create_connection(
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/socket.py", line 824, in create_connection
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
Thu Jun 8 13:44:38 2023 daemon.err uhttpd[2457]: LookupError: unknown encoding: idna
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: Traceback (most recent call last):
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 2004, in
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: main()
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1990, in main
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: shell()
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1876, in shell
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: speedtest = Speedtest(
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1095, in init
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: self.get_config()
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 1125, in get_config
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: uh, e = catch_request(request, opener=self._opener)
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 730, in catch_request
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: uh = _open(request)
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 519, in open
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 537, in http_open
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: return self.do_open(
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1282, in request
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/http/client.py", line 975, in send
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/bin/speedtest", line 426, in connect
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: self.sock = socket.create_connection(
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/socket.py", line 824, in create_connection
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
Thu Jun 8 13:44:39 2023 daemon.err uhttpd[2457]: LookupError: unknown encoding: idna

**Comment by OldCoding** [comment]
> LookupError: unknown encoding: idna

ssh登录路由，然后执行 sed '31 iimport encodings.idna' -i /usr/bin/speedtest  然后再试一下

**Comment by xiaoqi2020** [comment]
> > LookupError: unknown encoding: idna
> 
> ssh登录路由，然后执行 sed '31 iimport encodings.idna' -i /usr/bin/speedtest 然后再试一下

执行了，要重启吗？还是没有显示结果

**Comment by OldCoding** [comment]
> > > LookupError: unknown encoding: idna
> > 
> > 
> > ssh登录路由，然后执行 sed '31 iimport encodings.idna' -i /usr/bin/speedtest 然后再试一下
> 
> 执行了，要重启吗？还是没有显示结果

那这种情况可能需要作者来解决了@sirpdboy

**Comment by xiaoqi2020** [comment]
> > > > LookupError: unknown encoding: idna
> > > 
> > > 
> > > ssh登录路由，然后执行 sed '31 iimport encodings.idna' -i /usr/bin/speedtest 然后再试一下
> > 
> > 
> > 执行了，要重启吗？还是没有显示结果
> 
> 那这种情况可能需要作者来解决了@sirpdboy

好的，谢谢老板！

**Comment by sirpdboy** [comment]
编译的时候要选择 python3。

**Comment by allok1985** [comment]
> 编译的时候要选择python3。

刚开始以为安装python3就行，没效果
后来选择python3重新编译成功
现在大多云编译配置都很简略   建议这个写在说明里面

**Comment by allok1985** [comment]
netperf测速还是不行

**Comment by sirpdboy** [comment]
iperf3-ssl 的问题依赖已经修复   netperf测速没服务器了，取消。 python3默认带上依赖了。。
