### ISSUE TITLE
路由器上显示iperf3 服务端已停止。

### ISSUE THREAD

**Issue by 13810169** [sirpdboy/netspeedtest#4]
路由器上显示iperf3 服务端已停止。
下面选择 iperf 服务启动，之后点击执行操作按钮。
下面显示正在收集数据。

**Comment by loso3000** [comment]
点启动，是这样显示没状态没更新。下面收集数据等 待中是 表示 正常启动了。你可以刷新一下看状态 。

**Comment by qianfendou** [comment]
我也一样

**Comment by chenyajunai** [comment]
我也是

**Comment by sirpdboy** [comment]
刷新一下，或者重新点一下就会提示已经启动了 。

**Comment by jk2008chd** [comment]
如果是自己编译的话  要在make menuconfig中 network选用iperf3.

**Comment by sirpdboy** [comment]
新版本已经修复这 服务不实时的问题。
