### ISSUE TITLE
大佬这个只能x86用吗? 我的是arm 安装了没反应，应用也没显示

### ISSUE THREAD

**Issue by rq1025330** [sirpdboy/netspeedtest#6]

**Comment by sirpdboy** [comment]
ARM没机器，没测试，正常应该是可以。

**Comment by iuyaa** [comment]
上传文件到r2s里面，点安装显示Unknown packageXXXXX。

**Comment by masx200** [comment]
root@OpenWrt:~# ls /tmp/upload
luci-app-netspeedtest_2.1.1-20230116_all.ipk         luci-i18n-netspeedtest-zh-cn_2.1.1-20230116_all.ipk
root@OpenWrt:~# opkg install  /tmp/upload/luci-i18n-netspeedtest-zh-cn_2.1.1-20230116_all.ipk
Unknown package 'luci-i18n-netspeedtest-zh-cn'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-app-netspeedtest for luci-i18n-netspeedtest-zh-cn
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-i18n-netspeedtest-zh-cn found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-i18n-netspeedtest-zh-cn.
root@OpenWrt:~# opkg install  /tmp/upload/luci-app-netspeedtest_2.1.1-20230116_all.ipk  
Unknown package 'luci-app-netspeedtest'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency python3 for luci-app-netspeedtest
 * pkg_hash_check_unresolved: cannot find dependency iperf3 for luci-app-netspeedtest
 * pkg_hash_check_unresolved: cannot find dependency homebox for luci-app-netspeedtest
 * pkg_hash_check_unresolved: cannot find dependency netperf for luci-app-netspeedtest
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-netspeedtest found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-netspeedtest.
